/**
 * Generate components/icons.tsx from the captured icon inventory.
 *
 * The UI glyphs are Phosphor Icons Regular (MIT) — viewBox 0 0 256 256, a single
 * filled path, no stroke. Using them is fine. The Newt LOGO is hand-authored
 * pixel art and is deliberately excluded.
 *
 *   npx tsx tools/gen-icons.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Icon = {
  index: number
  viewBox: string
  classes?: string
  outerHTML: string
  host?: { title?: string; text?: string; tag?: string }
  nearestLabel?: string
}

const raw = JSON.parse(
  readFileSync(join(process.cwd(), 'docs/research/newt/icons.json'), 'utf8'),
) as Icon[]
const mobile = JSON.parse(
  readFileSync(join(process.cwd(), 'docs/research/newt/icons-390.json'), 'utf8'),
) as Icon[]

/** host title -> our component name. Anything unmapped is skipped. */
const NAME: Record<string, string> = {
  'File — new, recent, import': 'CaretDown',
  Settings: 'Sliders',
  'Smaller brush': 'Minus',
  'Bigger brush': 'Plus',
  'Pixel-perfect — remove doubled corners on diagonals': 'PixelPerfect',
  'Dither: Solid': 'CaretDownSmall',
  'Share — post to community, export PNG': 'Export',
  'Zoom out (⌘−)': 'Minus',
  'Zoom in (⌘+)': 'Plus',
  'Code & Export': 'Code',
  'Animation timeline': 'FilmStrip',
  Layers: 'Stack',
  'AI options': 'PlusCircleless',
  Send: 'ArrowUp',
  'Zoom out': 'Minus',
  'Zoom in': 'Plus',
  'Select / Move (V)': 'Cursor',
  'Brush (B)': 'PaintBrush',
  'Eraser (E)': 'Eraser',
  'Fill (G)': 'PaintBucket',
  'Shapes (U)': 'Square',
  'Select region (M)': 'Selection',
  'Eyedropper (I)': 'Eyedropper',
  'Gradient (H)': 'Gradient',
  Undo: 'ArrowUturnLeft',
  Redo: 'ArrowUturnRight',
  More: 'DotsThree',
}

const seen = new Map<string, string>() // name -> path d
const skipped: string[] = []

for (const icon of [...raw, ...mobile]) {
  if (icon.viewBox !== '0 0 256 256') {
    skipped.push(`${icon.host?.title ?? icon.nearestLabel ?? '?'} (viewBox ${icon.viewBox})`)
    continue
  }
  const title = icon.host?.title?.trim() ?? ''
  const name = NAME[title]
  if (!name) {
    skipped.push(`unmapped: "${title}"`)
    continue
  }
  const d = /<path[^>]*\sd="([^"]+)"/.exec(icon.outerHTML)?.[1]
  if (!d) {
    skipped.push(`${title} (no path d)`)
    continue
  }
  if (!seen.has(name)) seen.set(name, d)
}

const entries = [...seen.entries()].sort(([a], [b]) => a.localeCompare(b))

const out = `/**
 * Icons — Phosphor Icons Regular (MIT), viewBox 0 0 256 256, filled paths, no stroke.
 * https://phosphoricons.com/
 *
 * GENERATED by tools/gen-icons.ts from docs/research/newt/icons.json.
 * Do not hand-edit; re-run the generator instead.
 *
 * Sized by the caller via the \`size\` prop (16 / 20 / 24 px are the used values).
 * Colour comes from \`currentColor\`, so a parent's text colour drives the glyph.
 */

type IconProps = { size?: number; className?: string; style?: React.CSSProperties }

function make(d: string) {
  const C = ({ size = 20, className, style }: IconProps) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill="currentColor"
      aria-hidden="true"
      className={className}
      style={{ display: 'block', flex: 'none', ...style }}
    >
      <path d={d} />
    </svg>
  )
  return C
}

${entries.map(([name, d]) => `export const ${name} = make(\n  '${d}',\n)`).join('\n\n')}
`

writeFileSync(join(process.cwd(), 'components/icons.tsx'), out, 'utf8')

console.log(`wrote components/icons.tsx with ${entries.length} icons:`)
console.log('  ' + entries.map(([n]) => n).join(', '))
if (skipped.length) {
  console.log(`\nskipped ${skipped.length}:`)
  for (const s of [...new Set(skipped)]) console.log(`  - ${s}`)
}
