/**
 * Generate components/icons.tsx from the captured icon inventory.
 *
 * The UI glyphs are Phosphor Icons Regular (MIT) — viewBox 0 0 256 256, a single
 * filled path, no stroke. Using them is fine. The Newt LOGO is hand-authored
 * pixel art and is deliberately excluded.
 *
 *   npx tsx tools/gen-icons.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Icon = {
  index: number
  viewBox: string
  classes?: string
  outerHTML: string
  host?: { title?: string; text?: string; tag?: string }
  nearestLabel?: string
}

const raw = JSON.parse(
  readFileSync(join(process.cwd(), 'docs/research/newt/icons.json'), 'utf8'),
) as Icon[]
const mobile = JSON.parse(
  readFileSync(join(process.cwd(), 'docs/research/newt/icons-390.json'), 'utf8'),
) as Icon[]

/** host title -> our component name. Anything unmapped is skipped. */
const NAME: Record<string, string> = {
  'File — new, recent, import': 'CaretDown',
  Settings: 'Sliders',
  'Smaller brush': 'Minus',
  'Bigger brush': 'Plus',
  'Pixel-perfect — remove doubled corners on diagonals': 'PixelPerfect',
  'Dither: Solid': 'CaretDownSmall',
  'Share — post to community, export PNG': 'Export',
  'Zoom out (⌘−)': 'Minus',
  'Zoom in (⌘+)': 'Plus',
  'Code & Export': 'Code',
  'Animation timeline': 'FilmStrip',
  Layers: 'Stack',
  'AI options': 'PlusCircleless',
  Send: 'ArrowUp',
  'Zoom out': 'Minus',
  'Zoom in': 'Plus',
  'Select / Move (V)': 'Cursor',
  'Brush (B)': 'PaintBrush',
  'Eraser (E)': 'Eraser',
  'Fill (G)': 'PaintBucket',
  'Shapes (U)': 'Square',
  'Select region (M)': 'Selection',
  'Eyedropper (I)': 'Eyedropper',
  'Gradient (H)': 'Gradient',
  Undo: 'ArrowUturnLeft',
  Redo: 'ArrowUturnRight',
  More: 'DotsThree',
}

/**
 * Glyphs the reference never rendered, so they are not in the captured
 * inventory. Same source and licence — Phosphor Icons Regular, viewBox
 * 0 0 256 256, one filled path.
 *
 * `rotate` reuses an existing path turned about the centre, which is how
 * Phosphor itself relates CaretUp to CaretDown. Deriving it beats transcribing a
 * second path that has to stay in visual agreement with the first.
 */
const MANUAL: Record<string, { d: string; rotate?: number }> = {
  CaretUp: {
    d: 'M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z',
    rotate: 180,
  },
  Eye: {
    d: 'M247.31,124.76c-.35-.79-8.82-19.58-27.65-38.41C194.57,61.26,162.88,48,128,48S61.43,61.26,36.34,86.35C17.51,105.18,9,124,8.69,124.76a8,8,0,0,0,0,6.5c.35.79,8.82,19.57,27.65,38.4C61.43,194.74,93.12,208,128,208s66.57-13.26,91.66-38.34c18.83-18.83,27.3-37.61,27.65-38.4A8,8,0,0,0,247.31,124.76ZM128,192c-30.78,0-57.67-11.19-79.93-33.25A133.16,133.16,0,0,1,25,128,133.16,133.16,0,0,1,48.07,97.25C70.33,75.19,97.22,64,128,64s57.67,11.19,79.93,33.25A133.16,133.16,0,0,1,231.05,128C223.84,141.46,192.43,192,128,192Zm0-112a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160Z',
  },
  EyeSlash: {
    d: 'M53.92,34.62A8,8,0,1,0,42.08,45.38L61.32,66.55C25,88.84,9.38,123.2,8.69,124.76a8,8,0,0,0,0,6.5c.35.79,8.82,19.57,27.65,38.4C61.43,194.74,93.12,208,128,208a126.91,126.91,0,0,0,52.05-10.14l21.07,23.17a8,8,0,1,0,11.84-10.76Zm47.33,75.84,41.67,45.85a32,32,0,0,1-41.67-45.85ZM128,192c-30.78,0-57.67-11.19-79.93-33.25A133.16,133.16,0,0,1,25,128c4.69-8.79,19.66-33.39,47.35-49.38l18,19.75a48,48,0,0,0,63.66,70l14.73,16.2A112,112,0,0,1,128,192Zm6-95.43a8,8,0,0,1,3-15.72,48.16,48.16,0,0,1,38.77,42.64,8,8,0,0,1-7.22,8.71,6.39,6.39,0,0,1-.75,0,8,8,0,0,1-8-7.26A32.09,32.09,0,0,0,134,96.57Zm113.28,34.69c-.42.94-10.55,23.37-33.36,43.8a8,8,0,1,1-10.67-11.92A132.77,132.77,0,0,0,231.05,128c-7.21-13.46-38.62-64-103.05-64q-6.09,0-11.87.55A8,8,0,0,1,114.7,48.6Q120.94,48,128,48c34.88,0,66.57,13.26,91.66,38.35,18.83,18.83,27.3,37.62,27.65,38.4A8,8,0,0,1,247.31,131.26Z',
  },
}

const seen = new Map<string, string>() // name -> path d
const rotations = new Map<string, number>()
const skipped: string[] = []

for (const icon of [...raw, ...mobile]) {
  if (icon.viewBox !== '0 0 256 256') {
    skipped.push(`${icon.host?.title ?? icon.nearestLabel ?? '?'} (viewBox ${icon.viewBox})`)
    continue
  }
  const title = icon.host?.title?.trim() ?? ''
  const name = NAME[title]
  if (!name) {
    skipped.push(`unmapped: "${title}"`)
    continue
  }
  const d = /<path[^>]*\sd="([^"]+)"/.exec(icon.outerHTML)?.[1]
  if (!d) {
    skipped.push(`${title} (no path d)`)
    continue
  }
  if (!seen.has(name)) seen.set(name, d)
}

for (const [name, { d, rotate }] of Object.entries(MANUAL)) {
  if (seen.has(name)) continue
  seen.set(name, d)
  if (rotate) rotations.set(name, rotate)
}

const entries = [...seen.entries()].sort(([a], [b]) => a.localeCompare(b))

const out = `/**
 * Icons — Phosphor Icons Regular (MIT), viewBox 0 0 256 256, filled paths, no stroke.
 * https://phosphoricons.com/
 *
 * GENERATED by tools/gen-icons.ts from docs/research/newt/icons.json, plus the
 * MANUAL map in that generator for glyphs the reference never rendered.
 * Do not hand-edit; re-run the generator instead.
 *
 * Sized by the caller via the \`size\` prop (16 / 20 / 24 px are the used values).
 * Colour comes from \`currentColor\`, so a parent's text colour drives the glyph.
 */

type IconProps = { size?: number; className?: string; style?: React.CSSProperties }

function make(d: string, rotate = 0) {
  const C = ({ size = 20, className, style }: IconProps) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 256 256"
      fill="currentColor"
      aria-hidden="true"
      className={className}
      style={{ display: 'block', flex: 'none', ...style }}
    >
      <path d={d} transform={rotate ? \`rotate(\${rotate} 128 128)\` : undefined} />
    </svg>
  )
  return C
}

${entries
  .map(([name, d]) => {
    const rotate = rotations.get(name)
    return `export const ${name} = make(\n  '${d}',${rotate ? `\n  ${rotate},` : ''}\n)`
  })
  .join('\n\n')}
`

writeFileSync(join(process.cwd(), 'components/icons.tsx'), out, 'utf8')

console.log(`wrote components/icons.tsx with ${entries.length} icons:`)
console.log('  ' + entries.map(([n]) => n).join(', '))
if (skipped.length) {
  console.log(`\nskipped ${skipped.length}:`)
  for (const s of [...new Set(skipped)]) console.log(`  - ${s}`)
}
