/**
 * What the File menu is, and what it says. See docs/specs/17-file-menu.md.
 *
 * Same split as `canvas-size.ts`, and for the same reason (HANDOFF §11): a
 * control that lives entirely inside a `.tsx` has no CI guard, because `npm test`
 * runs in node and the browser probes need a dev server. So the *shape* of the
 * menu and every sentence it says are here, where a test can hold them, and
 * `components/Chrome.tsx` is left with markup and the calls that mutate.
 *
 * The three items the reference has and we do not — Dashboard, Explore,
 * Publish to community — are absent rather than disabled, and `SPEC.md §0` puts
 * them out permanently. `file-menu.test.ts` asserts they have not crept back,
 * because "we removed the accounts feature" is exactly the kind of decision that
 * gets undone by a later hand reaching for a familiar menu.
 */

import { paintedCellCount } from '../artwork-core/clear'
import type { Doc } from '../artwork-core/schema'
import type { StarterName } from '../artwork-core/create'

export type FileMenuItemId =
  | 'new'
  | 'recent'
  | 'open'
  | 'duplicate'
  | 'examples'
  | 'download'
  | 'png'
  | 'clear'

export type FileMenuItem = {
  id: FileMenuItemId
  label: string
  /**
   * The keyboard hint, and ONLY when that key is really wired.
   *
   * A hint is a promise about a key (§7.2). B1 shipped `Ctrl S` alone because
   * that was all that existed; B2 wired `Ctrl N` and `Ctrl O` and they appeared
   * in the same change. `Ctrl V` is still absent because Paste image is B3 —
   * `file-menu.test.ts` holds that line by asserting the hinted set exactly.
   */
  hint?: string
  /** Expands in place instead of running. §7.1 says why it is not a flyout. */
  submenu?: true
  /** Red, and confirms before it runs. */
  destructive?: true
}

/**
 * The menu, as groups. A divider is drawn *between* groups and never around an
 * empty one — spec §0: "a divider that exists only to separate an empty group is
 * worse than no divider".
 *
 * Paste image (B3) belongs in the first group and is not here yet. It is absent
 * rather than disabled for the same reason the account items are: a row that
 * looks like a control and does nothing is worse than no row.
 */
export const FILE_MENU: readonly (readonly FileMenuItem[])[] = [
  [
    { id: 'new', label: 'New…', hint: 'Ctrl N' },
    // Ordered as §1 draws it: recent sits directly under New, because the two
    // are the same question from opposite ends — start something, or go back to
    // something.
    { id: 'recent', label: 'Open recent', submenu: true },
    { id: 'open', label: 'Open…', hint: 'Ctrl O' },
    { id: 'duplicate', label: 'Duplicate' },
  ],
  [{ id: 'examples', label: 'Examples', submenu: true }],
  [
    // "Download", not "Export" — spec §7.6. Export is what the Code panel will
    // do to a different format, and one word for both acts would be ambiguous
    // in a menu that eventually carries six exporters.
    { id: 'download', label: 'Download .tessera.json', hint: 'Ctrl S' },
    { id: 'png', label: 'Export PNG' },
  ],
  [{ id: 'clear', label: 'Clear…', destructive: true }],
]

/** Flat, in visual order. Handy for "is every item reachable" checks. */
export const FILE_MENU_ITEMS: readonly FileMenuItem[] = FILE_MENU.flat()

/** `face` → `Face`. The submenu row's label; the starter names are the source. */
export const starterLabel = (name: StarterName): string =>
  name.charAt(0).toUpperCase() + name.slice(1)

// ─── DOM handles ─────────────────────────────────────────────────────────────

/**
 * The `id` each row carries, built here rather than written into the JSX.
 *
 * Two reasons, and the second is the one that cost time. First, HANDOFF §5: a
 * probe needs a handle that is not the accessible name when the name is the
 * thing under test, and an `aria-label` would override the visible name. Second,
 * B1 renamed `Example — face` and silently broke `probe-layers` and `probe-zoom`
 * — neither of which is about this menu, neither of which runs under
 * `npm test`. Both failed only when someone happened to run them.
 *
 * Because the component and `DOM_HANDLES` are now generated by the same
 * functions, `lib/__tests__/probe-handles.test.ts` can assert that every `#id`
 * the probes reach for still exists. A rename that orphans a probe now fails
 * `npm test` instead of waiting to be discovered.
 */
export const menuItemDomId = (id: FileMenuItemId): string => `file-${id}`
export const exampleDomId = (name: StarterName): string => `file-example-${name}`
export const CONFIRM_DOM_ID = { new: 'file-confirm-new', clear: 'file-confirm-clear' } as const

/**
 * The recent rows are keyed by document id, which is a nanoid — there is no
 * static handle for a row. So the *container* carries one and a probe reaches
 * rows through it (`#file-recent-list button`), which is also the honest
 * description: what is under test is the list, not any particular draft.
 */
export const RECENT_LIST_DOM_ID = 'file-recent-list'
export const RECENT_EMPTY_DOM_ID = 'file-recent-empty'

/** Every handle this menu renders, for the probe-handle test to check against. */
export function fileMenuDomHandles(starters: readonly StarterName[]): string[] {
  return [
    ...FILE_MENU_ITEMS.map((i) => menuItemDomId(i.id)),
    ...starters.map(exampleDomId),
    ...Object.values(CONFIRM_DOM_ID),
    RECENT_LIST_DOM_ID,
    RECENT_EMPTY_DOM_ID,
  ]
}

// ─── the two confirms ────────────────────────────────────────────────────────

/**
 * Whether New… has to ask. Spec F-M1.
 *
 * Blank in, no dialog: making someone confirm that they want to blank an
 * already-blank canvas is how a confirm becomes a thing people click through
 * without reading, which is the only way a confirm can actually fail.
 */
export const needsNewConfirm = (doc: Doc | null, frame: number): boolean =>
  !!doc && paintedCellCount(doc, frame) > 0

/** `143 painted pixels`, `1 painted pixel`. Shared so the two confirms agree. */
const pixels = (n: number): string => `${n} painted pixel${n === 1 ? '' : 's'}`

/**
 * New…, said honestly — §7.5, and a correction to §2 recorded in §7.11.
 *
 * §2 claims New "is not undoable through commit". It is, twice over now:
 * `new_document` commits a `replace_doc` carrying the whole previous document,
 * so Ctrl+Z brings the drawing back exactly, AND it forks to a fresh document
 * id, so the drawing keeps its own draft in IndexedDB and survives a reload.
 * Neither half was true when B1 first shipped; the sentence grew as the code
 * earned it, rather than the other way round.
 *
 * It still asks, because swapping the whole document under someone is worth a
 * beat even when nothing is lost — but it asks in the voice of something safe.
 */
export const newConfirm = (w: number, h: number): string =>
  `Start a blank ${w}×${h} canvas? This drawing is kept as its own draft, and undo brings it straight back.`

/**
 * Clear…, with its cost stated while the decision is still open.
 *
 * The shape A2 earned on the Canvas tab: say what it costs before the button,
 * not in a toast after. Clear is destructive-but-undoable exactly like a crop,
 * so it gets the crop's sentence rather than a scarier one.
 */
export const clearConfirm = (count: number): string =>
  `Clear ${pixels(count)} from every layer of this frame? Undo brings ${count === 1 ? 'it' : 'them'} back.`

/**
 * How a confirm's action button is painted.
 *
 * `danger` is red (`--diff-remove`) and means **this destroys work**. `primary`
 * is the product's standard action fill (`--solid`, per HANDOFF §8) and means
 * this is a big change that loses nothing.
 *
 * The distinction is load-bearing rather than decorative: New… wore red while
 * it overwrote the previous draft, and stopped deserving it the moment it forked
 * to its own id (§7.11). A red button that never costs anything is how a red
 * button stops meaning anything.
 */
export type ConfirmTone = 'danger' | 'primary'

/** The button inside each confirm. Says the verb, not "OK". */
export const CLEAR_ACTION = 'Clear frame'
export const CLEAR_TONE: ConfirmTone = 'danger'
export const NEW_ACTION = 'New canvas'
export const NEW_TONE: ConfirmTone = 'primary'
